# Merge airpot data into test data

In [1]:
import pandas as pd

In [4]:
# import both datasets as pandas DataFrame
astrike = pd.read_csv('airports_strikes.csv', index_col=0)
train = pd.read_csv('train_flights_Jan_1w.csv')

In [5]:
astrike.head()

,IATA,numflights,numstrikes,type,region,strikeprob,percentflights
0,ABE,12027,87.0,medium_airport,N,0.001977,0.000752
1,ABE,12027,5.0,medium_airport,N,0.000114,0.000752
2,ABI,4291,8.0,medium_airport,S,0.000182,0.000268
3,ABQ,54363,69.0,medium_airport,W,0.001568,0.003399
4,ABR,1492,21.0,medium_airport,M,0.000477,0.000093

In [6]:
train.head()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
0,2019-01-07,AA,AA_CODESHARE,AA,4432,YX,N446YX,4432,13495,MSY,...,675.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-02,WN,WN,WN,1181,WN,N556WN,1181,10397,ATL,...,874.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-08,DL,DL_CODESHARE,DL,6215,G7,N340CA,6215,13487,MSP,...,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-01,WN,WN,WN,1308,WN,N436WN,1308,12889,LAS,...,628.0,16.0,0.0,0.0,0.0,13.0,NaN,NaN,NaN,NaN
4,2019-01-06,HA,HA,HA,64,HA,N204HA,64,12982,LIH,...,2615.0,0.0,0.0,0.0,0.0,44.0,NaN,NaN,NaN,NaN

In [9]:
# process merge, drop duplicate column
train = train.merge(astrike, how='left', left_on='origin', right_on='IATA')
train.drop(['IATA'], axis=1, inplace=True)

In [10]:
train

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,type_x,region_x,strikeprob_x,percentflights_x,numflights_y,numstrikes_y,type_y,region_y,strikeprob_y,percentflights_y
0,2019-01-07,AA,AA_CODESHARE,AA,4432,YX,N446YX,4432,13495,MSY,...,large_airport,S,0.004590,0.007138,114148,202.0,large_airport,S,0.004590,0.007138
1,2018-01-02,WN,WN,WN,1181,WN,N556WN,1181,10397,ATL,...,large_airport,S,0.028133,0.049141,785850,1238.0,large_airport,S,0.028133,0.049141
2,2018-01-08,DL,DL_CODESHARE,DL,6215,G7,N340CA,6215,13487,MSP,...,large_airport,M,0.007340,0.020279,324301,323.0,large_airport,M,0.007340,0.020279
3,2019-01-01,WN,WN,WN,1308,WN,N436WN,1308,12889,LAS,...,large_airport,W,0.002704,0.020793,332518,119.0,large_airport,W,0.002704,0.020793
4,2019-01-06,HA,HA,HA,64,HA,N204HA,64,12982,LIH,...,medium_airport,O,0.000000,0.001767,28262,0.0,medium_airport,O,0.000000,0.001767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227214,2018-01-06,AA,AA_CODESHARE,AA,5165,OH,N540EA,5165,11995,GSO,...,medium_airport,S,0.003590,0.002214,35401,158.0,medium_airport,S,0.003590,0.002214
227215,2018-01-04,UA,UA_CODESHARE,UA,4324,EV,N14993,4324,11066,CMH,...,large_airport,M,0.009317,0.006163,98562,410.0,large_airport,M,0.009317,0.006163
227216,2019-01-06,DL,DL_CODESHARE,DL,5890,YX,N202JQ,5890,12953,LGA,...,large_airport,N,0.017498,0.021414,342443,770.0,large_airport,N,0.017498,0.021414
227217,2018-01-07,DL,DL_CODESHARE,DL,3564,OO,N256SY,3564,10713,BOI,...,medium_airport,W,0.002113,0.003137,50161,93.0,medium_airport,W,0.002113,0.003137
227218,2019-01-02,DL,DL,DL,1418,DL,N362NW,1418,11193,CVG,...,large_airport,S,0.014225,0.006463,103360,626.0,large_airport,S,0.014225,0.006463